# Trabalho 2 - Aprendizado Não Supervisionado

## Professor: Paulo Cotta

### Ideia do trabalho


Aprendizado não supervisionado para detecção de anomalias no preço das ações.
Temos um .csv que é o nosso dataset (conjunto de dados).

License of dataset: Anomaly detection in stock options pricing - MIT

In [9]:
import numpy as np
from sklearn.cluster import KMeans
import pandas as pd
import matplotlib.pyplot as plt
import seaborn
from sklearn.preprocessing import scale
seaborn.set()
%matplotlib inline

In [2]:
data = pd.read_csv("data.csv")
data.head()

,Unnamed: 0,UnderlyingPrice,OptionSymbol,Type,Expiration,DataDate,Strike,Last,Bid,Ask,...,OpenInterest,T1OpenInterest,IVMean,IVBid,IVAsk,Delta,Gamma,Theta,Vega,AKA
0,0,174.09,GS160108C00125000,call,01/08/2016,01/05/2016,125.0,0.0,46.95,50.80,...,0,0,0.0874,0.0,3.1911,1.0000,0.0000,0.0000,0.0000,GS160108C00125000
1,1,174.09,GS160108P00125000,put,01/08/2016,01/05/2016,125.0,0.0,0.00,0.31,...,0,0,1.9822,0.0,2.2141,-0.0150,0.0014,-0.2242,0.0053,GS160108P00125000
2,2,174.09,GS160108C00130000,call,01/08/2016,01/05/2016,130.0,0.0,41.80,45.80,...,0,0,0.0874,0.0,2.8946,1.0000,0.0000,0.0000,0.0000,GS160108C00130000
3,3,174.09,GS160108P00130000,put,01/08/2016,01/05/2016,130.0,0.0,0.00,0.31,...,0,0,1.7931,0.0,1.9882,-0.0175,0.0017,-0.2310,0.0060,GS160108P00130000
4,4,174.09,GS160108C00135000,call,01/08/2016,01/05/2016,135.0,0.0,36.95,40.90,...,0,0,0.0874,0.0,2.6480,1.0000,0.0000,0.0000,0.0000,GS160108C00135000

In [3]:
data.describe()

,Unnamed: 0,UnderlyingPrice,Strike,Last,Bid,Ask,Volume,OpenInterest,T1OpenInterest,IVMean,IVBid,IVAsk,Delta,Gamma,Theta,Vega
count,858.000000,8.580000e+02,858.000000,858.000000,858.000000,858.000000,858.000000,858.000000,858.000000,858.000000,858.000000,858.000000,858.000000,858.000000,858.000000,858.000000
mean,428.500000,1.740900e+02,186.463869,9.109988,20.894744,22.509755,20.349650,376.848485,384.405594,0.630892,0.159149,0.590690,-0.078274,0.008780,-0.077531,0.150592
std,247.827561,2.673199e-12,47.751953,19.266645,27.679726,29.122069,86.925383,1512.931102,1513.398965,2.198250,0.153752,0.517986,0.635420,0.010845,0.251748,0.214616
min,0.000000,1.740900e+02,80.000000,0.000000,0.000000,0.020000,0.000000,0.000000,0.000000,0.054600,0.000000,0.216900,-0.997000,0.000000,-3.366600,0.000000
25%,214.250000,1.740900e+02,152.500000,0.000000,0.360000,0.472500,0.000000,0.000000,0.000000,0.264750,0.000000,0.291025,-0.710300,0.001900,-0.069675,0.018050
50%,428.500000,1.740900e+02,185.000000,0.350000,7.925000,8.700000,0.000000,7.000000,9.000000,0.320950,0.214300,0.383200,0.001100,0.004700,-0.028850,0.062200
75%,642.750000,1.740900e+02,217.500000,7.662500,32.337500,35.800000,2.000000,136.500000,141.750000,0.451050,0.271050,0.634250,0.289025,0.011175,-0.012800,0.175275
max,857.000000,1.740900e+02,310.000000,113.000000,134.000000,138.800000,933.000000,21595.000000,21567.000000,37.111400,0.721600,3.242900,1.000000,0.079600,0.001000,0.991800

##### *Questão 1*

Quais são os dados de preços das ações no conjunto de dados? Explique e apresente abaixo apenas as colunas que contém tais dados.

In [7]:
# coloque o código aqui

#### *Questão 2*

*Aprendizado não supervisionado para encontrar discrepâncias (anomalias)*

Explique:

O que seria uma anomalia no dataset?

Para fins de detecção de anomalias, utilize algum algoritmo de aprendizado não supervisionado para identificar os cluster dos dados.

Exemplos de algoritmos não supervisionados:
- Isolation Forest
- K-Means
- KNN
- Randon Forest
- entre outros.

Apresente o código e detalhe, explicando a arquitetura criada/selecionada, além de apresentar dados de visualização (Data visualization [Utilizando Numpy, Pandas e Matplotlib]).

In [8]:
# o código aqui... ;)